src/TimesheetManagement/TimesheetManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('locations/', include("locations.urls")),
    path('workdays/', include("workdays.urls")),
    path('reports/', include("reports.urls"))
]

src/TimesheetManagement/reports/urls.py
from django.urls import path
from . import views

app_name = "reports"

urlpatterns = [
    path("", views.Report.as_view(), name="report"),
    path("export/", views.export, name="export"),
]

src/TimesheetManagement/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("new/", views.UserCreate.as_view(), name="create"),
    path("doctors/", views.DoctorList.as_view(), name="doctor_list"),
    path("doctors/<int:pk>/", views.DoctorDetail.as_view(), name="doctor_detail"),
    path("doctors/<int:pk>/update/", views.DoctorUpdate.as_view(), name="doctor_update"),
    path("doctors/<int:pk>/delete/", views.DoctorDelete.as_view(), name="doctor_delete"),
    path("admins/", views.AdminList.as_view(), name="admin_list"),
    path("admins/<int:pk>/", views.AdminDetail.as_view(), name="admin_detail"),
    path("admins/<int:pk>/update/", views.AdminUpdate.as_view(), name="admin_update"),
    path("admins/<int:pk>/delete/", views.AdminDelete.as_view(), name="admin_delete"),
    path(
        "login/", 
        auth_views.LoginView.as_view(
            template_name="users/login.html", 
            extra_context={"title": "Login"}
        ), 
        name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

src/TimesheetManagement/reports/models.py
from django.db import models

# Create your models here.

src/TimesheetManagement/reports/forms.py
from django import forms
from django.utils.timezone import now

class DateRangeForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.SelectDateWidget(years=tuple(range(2021, now().year + 2)))
    )
    end_date = forms.DateField(
        widget=forms.SelectDateWidget(years=tuple(range(2021, now().year + 2)))
    )

src/TimesheetManagement/reports/views.py
import csv
from django.http import HttpResponse
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from workdays.models import WorkDay
from django.utils.timezone import now
from datetime import datetime, timedelta
from .forms import DateRangeForm
from django.core.cache import cache


# Create your views here.
'''def export(request, query):
    query = tuple(map(int, query.split()))
    
    workdays = WorkDay.objects.filter(
        work_date__gte=datetime(query[2], query[0], query[1]),
        work_date__lte=datetime(query[5], query[3], query[4])
    )
    
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="report.csv"'

    writer = csv.writer(response)
    writer.writerow(
        ["work_date", "file_number", "employee_name", "time_in", 
        "time_out", "hours_worked", "location", "sector", 
        "hours_code", "fbp_payroll", "amco_payroll"
    ])
    
    for workday in workdays:
        writer.writerow([
            workday.work_date,
            workday.user.id,
            workday.user.full_name(),
            workday.time_in,
            workday.time_out,
            workday.hours_worked(),
            workday.location.name,
            workday.location.sector,
            workday.hours_code,
            workday.fbp_payroll,
            workday.amco_payroll
        ])

    return response
'''

def export(request):
    workdays = cache.get("export")

    
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="report.csv"'

    writer = csv.writer(response)
    writer.writerow(
        ["work_date", "file_number", "employee_name", "time_in", 
        "time_out", "hours_worked", "location", "sector", 
        "hours_code", "fbp_payroll", "amco_payroll"
    ])
    
    for workday in workdays:
        writer.writerow([
            workday.work_date,
            workday.user.id,
            workday.user.full_name(),
            workday.time_in,
            workday.time_out,
            workday.hours_worked(),
            workday.location.name,
            workday.location.sector,
            workday.hours_code,
            workday.fbp_payroll,
            workday.amco_payroll
        ])

    return response

class Report(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = WorkDay
    template_name = "reports/report.html"
    context_object_name = "workdays"
    extra_context = {"title": "Reports"}

    def get_context_data(self, object_list=None, *args, **kwargs):
        context = super().get_context_data(object_list=object_list, *args, **kwargs)
        context["search_form"] = DateRangeForm(
            initial={"start_date": now(), "end_date": now() + timedelta(days=14)}
        )
        return context
    
    def get_queryset(self):
        query = self.request.GET

        if query:
            start_date = f"{query.get('start_date_month')}-{query.get('start_date_day')}-{query.get('start_date_year')}"
            end_date = f"{query.get('end_date_month')}-{query.get('end_date_day')}-{query.get('end_date_year')}"

            queryset = WorkDay.objects.filter(
                work_date__gte=datetime.strptime(start_date, "%m-%d-%Y"),
                work_date__lte=datetime.strptime(end_date, "%m-%d-%Y")
            ).order_by("work_date", "time_in")
        else:
            queryset = WorkDay.objects.filter(work_date=now()).order_by("work_date", "time_in")

        cache.set("export", queryset)
        return queryset
    
    
    def test_func(self):
        return self.request.user.is_superuser

src/TimesheetManagement/reports/templates/reports/report.html
{% extends "base/base.html" %}

{% block content %}
    <form action="{% url 'reports:report' %}" method="get" class="mt-3">
        {{ search_form.as_p }}
        <button type="submit" class="btn btn-secondary">Search</button>
    </form>

    {% if workdays %}
    <table class="table mt-4">
        <thead>
            <tr>
                <th>Work Date</th>
                <th>Employee</th>
                <th>Location</th>
                <th>Time In</th>
                <th>Time Out</th>
                <th>Hours Worked</th>
                <th>Hours Code</th>
                <th>FBP Payroll</th>
                <th>AMCO Payroll</th>
            </tr>
        </thead>    
            {% for workday in workdays %}    
            <tbody>
                <tr>
                    <td>{{ workday.work_date }}</td>
                    <td>{{ workday.user }}</td>
                    <td>{{ workday.location}}</td>
                    <td>{{ workday.time_in }}</td>
                    <td>{{ workday.time_out }}</td>
                    <td>{{ workday.hours_worked }}</td>
                    <td>{{ workday.hours_code }}</td>
                    <td>${{ workday.fbp_payroll }}</td>
                    <td>${{ workday.amco_payroll }}</td>
                </tr>
            </tbody>    
            {% endfor %}
        </table>

        <h4><a href="{% url 'reports:export' %}" class="btn btn-success">Export</a></h4>
    {% else %}
        <h1 class="text-center">Either no search was conducted or no workdays met the criteria.</h1>
    {% endif %}
{% endblock content %}