src/TimesheetManagement/TimesheetManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('locations/', include("locations.urls")),
    path('workdays/', include("workdays.urls")),
    path('reports/', include("reports.urls"))
]

src/TimesheetManagement/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("new/", views.UserCreate.as_view(), name="create"),
    path("doctors/", views.DoctorList.as_view(), name="doctor_list"),
    path("doctors/<int:pk>/", views.DoctorDetail.as_view(), name="doctor_detail"),
    path("doctors/<int:pk>/update/", views.DoctorUpdate.as_view(), name="doctor_update"),
    path("doctors/<int:pk>/delete/", views.DoctorDelete.as_view(), name="doctor_delete"),
    path("admins/", views.AdminList.as_view(), name="admin_list"),
    path("admins/<int:pk>/", views.AdminDetail.as_view(), name="admin_detail"),
    path("admins/<int:pk>/update/", views.AdminUpdate.as_view(), name="admin_update"),
    path("admins/<int:pk>/delete/", views.AdminDelete.as_view(), name="admin_delete"),
    path(
        "login/", 
        auth_views.LoginView.as_view(
            template_name="users/login.html", 
            extra_context={"title": "Login"}
        ), 
        name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

src/TimesheetManagement/workdays/urls.py
from django.urls import path
from . import views

app_name = "workdays"

urlpatterns = [
    path("", views.WorkDayList.as_view(), name="list"),
    path("new/", views.WorkDayCreate.as_view(), name="create"),
    path("<int:pk>/", views.WorkDayDetail.as_view(), name="detail"),
    path("<int:pk>/update/", views.WorkDayUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", views.WorkDayDelete.as_view(), name="delete"),
]

src/TimesheetManagement/workdays/models.py
from django.db import models
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.urls import reverse
from locations.models import Location
from datetime import date, time, datetime, timedelta


HOUR_CODES = (("FBP", "FBP"), ("AMCO", "AMCO"))

class WorkDay(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, null=True, on_delete=models.SET_NULL)
    work_date = models.DateField(null=False, default=now)
    time_in = models.TimeField(null=False, default=time(hour=8))
    time_out = models.TimeField(null=False, default=time(hour=16))
    hours_code = models.CharField(
        null=False, 
        max_length=4, 
        choices=HOUR_CODES,
        validators=[
            RegexValidator(
                regex="^(FBP|AMCO)$",
                message="Please choose either FBP or AMCO."
            )
        ]
    )
    fbp_payroll = models.DecimalField(
        max_digits=9, 
        decimal_places=2, 
        null=False, 
        default=0,
        validators=[
            MinValueValidator(
                limit_value=0, 
                message="Please insert a non-negative number."
            ),
            MaxValueValidator(
                limit_value=9999999.99, 
                message="Payroll must be under $10 million."
            )
        ]
    )
    amco_payroll = models.DecimalField(
        max_digits=9, 
        decimal_places=2, 
        null=False, 
        default=0,
        validators=[
            MinValueValidator(
                limit_value=0, 
                message="Please insert a non-negative number."
            ),
            MaxValueValidator(
                limit_value=9999999.99, 
                message="Payroll must be under $10 million."
            )
        ]
    )
    date_created = models.DateTimeField(null=False, default=now)

    def __str__(self):
        return f"{self.user.full_name()}: {self.work_date} ({self.time_in}-{self.time_out})"

    def hours_worked(self):
        date_ = date(1, 1, 1)
        datetime1 = datetime.combine(date_, self.time_in)
        datetime2 = datetime.combine(date_, self.time_out)
        return datetime2 - datetime1
    
    def is_locked(self):
        return now() > self.date_created + timedelta(days=45)
    
    def get_absolute_url(self):
        return reverse("workdays:list")
    
    @property
    def get_html_url(self):
        url = reverse('workdays:detail', args=(self.id,))
        return f'<a href="{url}">{self.time_in} - {self.time_out} {self.location}</a>'

src/TimesheetManagement/workdays/forms.py
from django import forms
from .models import WorkDay

class WorkDayForm(forms.ModelForm):
    work_date = forms.DateField(widget=forms.SelectDateWidget())
    time_in = forms.TimeField(widget=forms.TimeInput())
    time_out = forms.TimeField(widget=forms.TimeInput())

    class Meta:
        model = WorkDay
        exclude = ["date_created"]

src/TimesheetManagement/workdays/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, UserPassesTestMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import WorkDay
from .forms import WorkDayForm
from django.contrib.auth.models import User
from django.core.cache import cache
from .utils import Calendar
from django.utils.safestring import mark_safe
from datetime import datetime, date, timedelta
import calendar

# Create your views here.
def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

class WorkDayList(LoginRequiredMixin, ListView):
    model = WorkDay
    template_name = "workdays/list.html"
    context_object_name = "workdays"
    ordering = ["work_date"]
    extra_context = {"title": "List of Work Days"}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(query=context["workdays"], withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        if context.get("workdays"):
            context["user_full_name"] = context["workdays"][0].user.full_name
        return context
    
    def get_queryset(self):
        if self.request.user.is_superuser:
            cached_queryset = cache.get("workdays")
            if cached_queryset:
                cached_first_name, cached_last_name = cache.get("full_name")
                if (self.request.GET.get("first_name") == cached_first_name and self.request.GET.get("last_name") == cached_last_name) or (not self.request.GET.get("first_name") and not self.request.GET.get("last_name")):
                    return cached_queryset
                else:
                    cache.delete("workdays")
                    cache.delete("full_name")

            first_name = self.request.GET.get("first_name")
            last_name = self.request.GET.get("last_name")
            
            if first_name and last_name:
                user_ = User.objects.filter(
                    first_name__icontains=first_name.strip(),
                    last_name__icontains=last_name.strip()
                )
            elif first_name:
                user_ = User.objects.filter(first_name__icontains=first_name.strip())
            elif last_name:
                user_ = User.objects.filter(last_name__icontains=last_name.strip())
            else:
                user_ = User.objects.none()

            if user_:
                queryset = WorkDay.objects.filter(user=user_[0]).order_by("work_date", "time_in")
                cache.set("workdays", queryset)
                cache.set("full_name", (first_name, last_name))
                return queryset
            else:
                return WorkDay.objects.none()
        else:
            return WorkDay.objects.filter(user=self.request.user).order_by("work_date", "time_in")
            

class WorkDayCreate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, CreateView):
    model = WorkDay
    template_name = "workdays/new_or_update.html"
    extra_context = {"title": "New Work Day"}
    form_class = WorkDayForm
    success_message = "Workday was successfully created!"

    def test_func(self):
        return self.request.user.is_superuser


class WorkDayDetail(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = WorkDay
    template_name = "workdays/detail.html"
    context_object_name = "workday"
    extra_context = {"title": "Work Day Information"}

    def test_func(self):
        return self.request.user.is_superuser or self.get_object().user == self.request.user


class WorkDayUpdate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = WorkDay
    template_name = "workdays/new_or_update.html"
    extra_context = {"title": "Update Work Day"}
    form_class = WorkDayForm
    success_message = "Workday was successfully updated!"

    def test_func(self):
        return self.request.user.is_superuser and not self.get_object().is_locked()


class WorkDayDelete(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = WorkDay
    template_name = "workdays/delete.html"
    extra_context = {"title": "Delete Work Day"}
    success_url = reverse_lazy("workdays:list")
    success_message = "Workday was successfully deleted!"

    def test_func(self):
        return self.request.user.is_superuser and not self.get_object().is_locked()

src/TimesheetManagement/workdays/templates/workdays/create.html
{% extends "base/form.html" %}

{% block back_button %}
    <a href="{% url 'workdays:list' %}">Back</a>
{% endblock back_button %}

src/TimesheetManagement/workdays/templates/workdays/delete.html
{% extends "base/confirm_delete.html" %}

{% block back_button %}
    <a href="{% url 'workdays:detail' workday.id %}">Back</a>
{% endblock back_button %}

src/TimesheetManagement/workdays/templates/workdays/detail.html
{% extends "base/base.html" %}

{% block content %}
    <p><b>Work Day:</b> {{ workday.work_date }}</p>
    <p><b>Employee:</b> {{ workday.user.full_name }}</p>
    <p><b>Location:</b> {{ workday.location }}</p>
    <p><b>Time In:</b> {{ workday.time_in }}</p>   
    <p><b>Time Out:</b> {{ workday.time_out }}</p>
    <p><b>Hours Code:</b> {{ workday.hours_code }}</p>
    <p><b>FBP Payroll:</b> ${{ workday.fbp_payroll }}</p>
    <p><b>AMCO Payroll:</b> ${{ workday.amco_payroll }}</p>
    <p>
        <b>Date Created:</b> {{ workday.date_created }}
        {% if workday.is_locked %} <b>(LOCKED)</b> {% endif %}
    </p>

    {% if user.is_superuser and not workday.is_locked %}
        <p><a href="{% url 'workdays:update' workday.id %}">Update</a></p>
        <p><a href="{% url 'workdays:delete' workday.id %}">Delete</a></p>
    {% endif %}

    <h4><a href="{% url 'workdays:list' %}">Back</a></h4>
{% endblock content%}

src/TimesheetManagement/workdays/templates/workdays/list.html
{% extends "base/base.html" %}

{% block content %}
    {% if user.is_superuser %}
    <form class="text-center" action="{% url 'workdays:list' %}" method="get">
        <input name="first_name" type="text" placeholder="Search first name">
        <input name="last_name" type="text" placeholder="Search last name">
        <button type="submit" class="btn btn-secondary">Search</button>
    </form>
    {% endif %}

    {% if workdays %}
        <h1 class="text-center">Dr. {{ user_full_name }}</h1>
        <div class="clearfix">
            <a class="btn btn-info right mr-2" href="{% url 'workdays:list' %}?{{ next_month }} ">Next Month >></a>
            <a class="btn btn-info right mr-2" href="{% url 'workdays:list' %}?{{ prev_month }}"><< Previous Month</a>
        </div>
        <div style="color: blueviolet;">
            {{ calendar }}
        </div>
    {% else %}
        {% if user.is_superuser %}
            <h5 class="text-center m-5">Either no search was conducted or no workdays are available.</h5>
        {% else %}
            <h5 class="text-center m-5">No workdays are listed at this time.</h5>
        {% endif %}
    {% endif %}
    
    {% if user.is_superuser %}
        <h4><a href="{% url 'workdays:create' %}" class="btn btn-primary">Add Work Day</a></h4>
    {% endif %}
{% endblock content%}

src/TimesheetManagement/workdays/templates/workdays/list_copy.html
{% extends "base/base.html" %}

{% block content %}
    {% if user.is_superuser %}
    <form action="{% url 'workdays:list' %}" method="get">
        <input name="first_name" type="text" placeholder="Search first name">
        <input name="last_name" type="text" placeholder="Search last name">
        <button type="submit" class="btn btn-secondary">Search</button>
    </form>
    {% endif %}

    {% if workdays %}
        <table class="table mt-4">
            <thead>
                <tr>
                    <th>Work Date</th>
                    <th>Employee</th>
                    <th>Location</th>
                    <th>Time In</th>
                    <th>Time Out</th>
                    <th>Hours Code</th>
                    <th>FBP Payroll</th>
                    <th>AMCO Payroll</th>
                    <th colspan="3">Actions</th>
                </tr>
            </thead>
            {% for workday in workdays %}   
            <tbody>
                <tr>
                    <td>{{ workday.work_date }}</td>
                    <td>{{ workday.user }}</td>
                    <td>{{ workday.location }}</td>
                    <td>{{ workday.time_in }}</td>
                    <td>{{ workday.time_out }}</td>
                    <td>{{ workday.hours_code }}</td>
                    <td>${{ workday.fbp_payroll }}</td>
                    <td>${{ workday.amco_payroll }}</td>
                    <td><a href="{% url 'workdays:detail' workday.id %}" class="btn btn-success">View</a></td>
                    
                    {% if user.is_superuser and not workday.is_locked %}
                        <td><a href="{% url 'workdays:update' workday.id %}" class="btn btn-primary">Update</a></td>
                        <td><a href="{% url 'workdays:delete' workday.id %}" class="btn btn-danger">Delete</a></td>
                    {% else %}
                        <td></td>
                        <td></td>
                    {% endif %}
                </tr>
            </tbody>                 
            {% endfor %}
        </table>
    {% else %}
        {% if user.is_superuser %}
            <h5 class="m-5">Either no search was conducted or no workdays are available.</h5>
        {% else %}
            <h5 class="m-5">No workdays are listed at this time.</h5>
        {% endif %}
    {% endif %}
    
    {% if user.is_superuser %}
        <h4><a href="{% url 'workdays:create' %}" class="btn btn-primary">Add Work Day</a></h4>
    {% endif %}
{% endblock content%}

src/TimesheetManagement/workdays/templates/workdays/new_or_update.html
{% extends "base/form.html" %}

{% block back_button %}
    <a href="{% url 'workdays:list' %}">Back</a>
{% endblock back_button %}