src/TimesheetManagement/TimesheetManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('locations/', include("locations.urls")),
    path('workdays/', include("workdays.urls")),
    path('reports/', include("reports.urls"))
]

src/TimesheetManagement/locations/urls.py
from django.urls import path
from . import views

app_name = "locations"

urlpatterns = [
    path("", views.LocationList.as_view(), name="list"),
    path("new/", views.LocationCreate.as_view(), name="create"),
    path("<int:pk>/update/", views.LocationUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", views.LocationDelete.as_view(), name="delete"),
]

src/TimesheetManagement/reports/urls.py
from django.urls import path
from . import views

app_name = "reports"

urlpatterns = [
    path("", views.Report.as_view(), name="report"),
    path("export/", views.export, name="export"),
]

src/TimesheetManagement/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("new/", views.UserCreate.as_view(), name="create"),
    path("doctors/", views.DoctorList.as_view(), name="doctor_list"),
    path("doctors/<int:pk>/", views.DoctorDetail.as_view(), name="doctor_detail"),
    path("doctors/<int:pk>/update/", views.DoctorUpdate.as_view(), name="doctor_update"),
    path("doctors/<int:pk>/delete/", views.DoctorDelete.as_view(), name="doctor_delete"),
    path("admins/", views.AdminList.as_view(), name="admin_list"),
    path("admins/<int:pk>/", views.AdminDetail.as_view(), name="admin_detail"),
    path("admins/<int:pk>/update/", views.AdminUpdate.as_view(), name="admin_update"),
    path("admins/<int:pk>/delete/", views.AdminDelete.as_view(), name="admin_delete"),
    path(
        "login/", 
        auth_views.LoginView.as_view(
            template_name="users/login.html", 
            extra_context={"title": "Login"}
        ), 
        name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

src/TimesheetManagement/workdays/urls.py
from django.urls import path
from . import views

app_name = "workdays"

urlpatterns = [
    path("", views.WorkDayList.as_view(), name="list"),
    path("new/", views.WorkDayCreate.as_view(), name="create"),
    path("<int:pk>/", views.WorkDayDetail.as_view(), name="detail"),
    path("<int:pk>/update/", views.WorkDayUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", views.WorkDayDelete.as_view(), name="delete"),
]

src/TimesheetManagement/templates/base/administration_sidebar.html
{% extends "base/base.html" %}

{% block sidebar %}
    <h4><a href="{% url 'users:admin_list' %}">Users</a></h4>
    <h4><a href="{% url 'workdays:list' %}">Time Cards</a></h4>
    <h4><a href="{% url 'locations:list' %}">Locations</a></h4>
{% end sidebar %}

src/TimesheetManagement/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}">
    {% if title %}
            <title>Time Management - {{ title }}</title>
        {% else %}
            <title>Time Management</title>
        {% endif %}
</head>
<body>
    <div>
        <div class="row">
          <div class="col-sm rounded-bottom bg-primary text-white text-center">
              <div class="p-3 mt-4">
                <h1>TIMECARD</h1><br>
                <h3>Data Entry System</h3>
                
              </div>
          </div>
          <div class="col-sm rounded-bottom">
            <img src="{% static 'images/doctor.jpg' %}" class="img-thumbnail rounded" alt="doctor image">
          </div>
          <div class="col-sm rounded-bottom bg-primary text-white p-2 text-center">
              <div class="p-3 mt-4">
                <h3>Welcome, {% if user.is_authenticated%} {{ user.full_name }} {% endif %}</h3>
                <!--<p>Monday, June, 2020</p>-->
                <p>{{ today_date }}</p> 
                {% if user.is_authenticated %}
                <a class="nav-link text-white" href="{% url 'users:logout' %}">Logout {{ users.user_.username }}</a>
                {% endif %}
              </div>
          </div>
        </div>
        {% if user.is_authenticated %}
        <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div>
                <ul class="navbar-nav text-white">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:admin_list' %}">Administration</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'workdays:list' %}">Time Card Managment</a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:report' %}">Reports</a>
                </li>
                {% endif %}
                </ul>
            {% endif %}
            </div>

        </nav>
        </div>
        <div class="container">
            {% if title %}
                <h1>{{ title }}</h1>
            {% endif %}

            <div class="col-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            {% block content %}{% endblock content %}
        </div>
        </div>
    </body>
</html>

src/TimesheetManagement/templates/base/confirm_delete.html
{% extends "base/base.html" %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
            <h3>Are you sure you want to delete "{{ object }}"?</h3>
            <button  type="submit">Delete</button>
    </form>
    {% block back_button %}{% endblock back_button %}
{% endblock content %}

src/TimesheetManagement/templates/base/form copy.html
{% extends "base/base.html" %}
{% load widget_tweaks %}

{% block content %}
    <form enctype="multipart/form-data" method="POST" class="form-horizontal">
        {% csrf_token %}
        {% if user_form and profile_form %}
            {% for field in user_form %}
            <div class="form-group col-xs-4">
                {{ field.label_tag}}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}

            {% for field in profile_form %}
            <div class="form-group col-xs-4">
                {{ field.label_tag}}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}

        {% else %}
            {% for field in form %}
            <div class="form-group col-xs-4">
                {{ field.label_tag}}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}
        {% endif %}
        <button class="btn btn-primary mt-3" type="submit">Submit</button>
    </form>
    {% block back_button %}{% endblock back_button %}
{% endblock content %}

src/TimesheetManagement/templates/base/form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form enctype="multipart/form-data" method="POST" class="form-horizontal">
        {% csrf_token %}
        {% if user_form and profile_form %}
            <div class="form-group col-xs-4">
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
            </div>
        {% else %}
            <div class="form-group col-xs-4">
                {{ form|crispy }}
            </div>
        {% endif %}
        <button class="btn btn-primary mt-3" type="submit">Submit</button>
    </form>
    {% block back_button %}{% endblock back_button %}
{% endblock content %}

src/TimesheetManagement/templates/base/home.html
{% extends "base/base.html" %}

{% block content %}
    {% if user.is_superuser %}
        <h4><a href="{% url 'users:doctor_list' %}">Manage Employees</a></h4>
    {% endif %}
{% endblock content %}