src/TimesheetManagement/TimesheetManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('locations/', include("locations.urls")),
    path('workdays/', include("workdays.urls")),
    path('reports/', include("reports.urls"))
]

src/TimesheetManagement/locations/urls.py
from django.urls import path
from . import views

app_name = "locations"

urlpatterns = [
    path("", views.LocationList.as_view(), name="list"),
    path("new/", views.LocationCreate.as_view(), name="create"),
    path("<int:pk>/update/", views.LocationUpdate.as_view(), name="update"),
    path("<int:pk>/delete/", views.LocationDelete.as_view(), name="delete"),
]

src/TimesheetManagement/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path("new/", views.UserCreate.as_view(), name="create"),
    path("doctors/", views.DoctorList.as_view(), name="doctor_list"),
    path("doctors/<int:pk>/", views.DoctorDetail.as_view(), name="doctor_detail"),
    path("doctors/<int:pk>/update/", views.DoctorUpdate.as_view(), name="doctor_update"),
    path("doctors/<int:pk>/delete/", views.DoctorDelete.as_view(), name="doctor_delete"),
    path("admins/", views.AdminList.as_view(), name="admin_list"),
    path("admins/<int:pk>/", views.AdminDetail.as_view(), name="admin_detail"),
    path("admins/<int:pk>/update/", views.AdminUpdate.as_view(), name="admin_update"),
    path("admins/<int:pk>/delete/", views.AdminDelete.as_view(), name="admin_delete"),
    path(
        "login/", 
        auth_views.LoginView.as_view(
            template_name="users/login.html", 
            extra_context={"title": "Login"}
        ), 
        name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

src/TimesheetManagement/locations/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse
from django.utils.timezone import now
from datetime import timedelta

SECTORS = (("E", "East"), ("W", "West"))

# Create your models here.
class Location(models.Model):
    name = models.CharField(
        unique=True,
        max_length=30, 
        null=False,
        validators=[
            RegexValidator(
                regex="^[a-zA-Z0-9,\. :-]+$",
                message="Please insert a valid location name."
            )
        ]
    )
    sector = models.CharField(
        max_length=1, 
        null=False, 
        choices=SECTORS,
        validators=[
            RegexValidator(
                regex="^[EW]$",
                message="Please insert either E (East) or W (West)."
            )
        ]
    )
    date_created = models.DateTimeField(null=False, default=now)

    def __str__(self):
        return f"{self.name} ({self.sector})"

    def is_locked(self):
        return now() > self.date_created + timedelta(days=45)

    def get_absolute_url(self):
        return reverse("locations:list")

src/TimesheetManagement/locations/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, UserPassesTestMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, FormView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from .models import Location

# Create your views here.
class LocationList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Location
    template_name = "locations/list.html"
    context_object_name = "locations"
    ordering = ["name", "sector"]
    extra_context = {"title": "List of Locations"}

    def test_func(self):
        return self.request.user.is_superuser
        
    def get_queryset(self):
        query = self.request.GET.get("search")
        if query:
            return Location.objects.filter(name__icontains=query.strip()).order_by("name", "sector")
        else:
            return super().get_queryset()

class LocationCreate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, CreateView):
    model = Location
    fields = ["name", "sector"]
    template_name = "locations/new_or_update.html"
    extra_context = {"title": "New Location"}
    success_message = "Location was successfully created!"

    def test_func(self):
        return self.request.user.is_superuser


class LocationUpdate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Location
    fields = ["name", "sector"]
    template_name = "locations/new_or_update.html"
    extra_context = {"title": "Update Location"}
    success_message = "Location was successfully updated!"

    def test_func(self):
        return self.request.user.is_superuser and not self.get_object().is_locked()


class LocationDelete(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = Location
    template_name = "locations/delete.html"
    extra_context = {"title": "Delete Location"}
    success_url = reverse_lazy("locations:list")
    success_message = "Location was successfully deleted!"

    def test_func(self):
        return self.request.user.is_superuser and not self.get_object().is_locked()

src/TimesheetManagement/locations/templates/locations/delete.html
{% extends "base/confirm_delete.html" %}

{% block back_button %}
    <a href="{% url 'locations:list' %}">Back</a>
{% endblock back_button %}

src/TimesheetManagement/locations/templates/locations/list.html
{% extends "base/base.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-between mt-2">
        <div class="col-sm-2 bg-primary text-white rounded pt-3">
            <div>
                <ul class="navbar-nav text-white">
                  <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'users:admin_list' %}">Users</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'locations:list' %}">Location</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'users:doctor_list' %}">Doctors</a>
                  </li>
                </ul>
              </div> 
        </div>
        <div class="col-sm-9">
            <form action="{% url 'locations:list' %}" method="get">
                <input name="search" type="text" placeholder="Search locations">
                <button type="submit" class="btn btn-secondary">Search</button>
            </form>
            {% if locations %}
            <table class="table mt-4">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Sector</th>
                    <th scope="col">Date Created</th>
                    <th colspan="2">Actions</th>
                </tr>
                </thead>
                {% for location in locations %}    
                <tbody>
                    <tr>
                        <td>{{ location.name }}</td>
                        <td>
                            {% if location.sector == "E" %}
                                East
                            {% elif location.sector == "W" %}
                                West
                            {% endif %}
                        </td>
                        <td>
                            {{ location.date_created }}
                            {% if location.is_locked %} <b>(LOCKED)</b> {% endif %}
                        </td>
                        
                        {% if user.is_superuser and not location.is_locked %}
                            <td><a href="{% url 'locations:update' location.id %}" class="btn btn-primary">Update</a></td>
                            <td><a href="{% url 'locations:delete' location.id %}" class="btn btn-danger">Delete</a></td>
                        {% else %}
                            <td></td>
                            <td></td>    
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
                <h1>No locations are listed at this time.</h1>
            {% endif %}
        
            <h4><a href="{% url 'locations:create' %}" class="btn btn-primary">Add Location</a></h4>
        </div>
</div>
    
{% endblock content %}

src/TimesheetManagement/locations/templates/locations/new_or_update.html
{% extends "base/form.html" %}

{% block back_button %}
    <a href="{% url 'locations:list' %}">Back</a>
{% endblock back_button %}